/// Flutter icons DmHelder
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DmHelder
///      fonts:
///       - asset: fonts/DmHelder.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DmHelder {
  DmHelder._();

  static const _kFontFam = 'DmHelder';
  static const String? _kFontPkg = null;

  static const IconData amorclassicon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backicon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData campaignsicon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData combaticon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editicon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData optionsicon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saveicon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
